{
  "errors": [
    {
      "id": "123456",
      "status": "422",
      "code": "123",
      "title": "A custom json:api error occurred",
      "detail": "Details about the error",
      "source": {
        "pointer": "/data/attributes/first-name"
      },
      "meta": {
        "message": "A custom json:api error occurred",
        "exception": "WtfPhp\\JsonApiErrors\\Exceptions\\JsonApiErrorException",
        "file": "/json-api-errors/tests/JsonApiErrorMultipleMiddlewareTest.php",
        "line": 440,
        "trace": { }
      }
    }
  ]
}
